### PR TITLE
[DOCS] adding license to the bower.json

### PR DESCRIPTION
**Pull request by williamsbdev**
I need this change to allow the `bower-license` node module to check all the licenses on our bower dependencies for a security audit. If you would be so kind as to also bump the version and do a bug fix release version, it would help. Thanks!

### CODE REVIEW

**Comment by williamsbdev** [comment]
The build appears to have failed as it was unable to open a tunnel to saucelabs. Will a maintainer please try running the build again?

**Comment by FagnerMartinsBrack** [comment]
@williamsbdev Can you upgrade to [js-cookie v2](https://github.com/js-cookie/js-cookie/releases) and open this issue in that repo? We are not maintaining jquery-cookie anymore.

**Comment by williamsbdev** [comment]
I would love to but apparently the version that we are using is 1.4.1 through as a transient dependency of foundation. I will look into foundation and see I can use a newer version or they can stop using this deprecated library in favor of the new one.

Thanks!

**Comment by FagnerMartinsBrack** [comment]
Let us know the solution you found :+1:

**Pull request closed without merging**
