### PR TITLE
Really remove cookie whether it's created with an default domain or not

### PR DESCRIPTION
**Pull request by ryoqun**
This fixes the following insanity:

screen shot 2015-03-02 at 7 02 21 pm

### CODE REVIEW

**Comment by Krinkle** [comment]
Shouldn't the application code be responsible for being consistent in how it creates, updates and removes cookies with the same options?

**Comment by carhartl** [comment]
I think so too @Krinkle. Default options may help with this.

**Comment by FagnerMartinsBrack** [comment]
The docs says `// Returns true when cookie was successfully deleted, otherwise false`.

That seems to be misleading, shouldn't it be `// Returns true when target cookie exists, but may not be deleted if options were not passed correctly`, or enforce somewhere that `The behavior for passing wrong options to $.removeCookie is undefined` (this is implicit, but still an abstraction leak from the browser default cookie mechanism, if we consider that this behavior should be known by the developer).

**Comment by carhartl** [comment]
The documentations says:

> when deleting a cookie, you must pass the exact same path, domain and secure options that were used to set the cookie

I want to keep it that way, otherwise we'd be expected to do the same for  `path` at some point, adding even more code...

Thanks for the PR, but closing.

**Pull request closed without merging**
