### PR TITLE
Download hint specificially for volo

### PR DESCRIPTION
**Pull request by wilmoore**

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @wilmoore, can you confirm if this is still working?

https://raw.github.com/carhartl/jquery-cookie/v1.4.1/src/jquery.cookie.js doesn't seems to be working via GET request, it returns 404.

**Comment by carhartl** [comment]
@FagnerMartinsBrack That link works for me.

**Comment by FagnerMartinsBrack** [comment]
@carhartl Isn't cached for you due to previous access?

**Comment by carhartl** [comment]
Ah yes, I see, there's 301, the new location is https://raw.githubusercontent.com/carhartl/jquery-cookie/v1.4.1/src/jquery.cookie.js, but that gives a 404... I don't get why.

https://developer.github.com/changes/2014-04-25-user-content-security/

**Comment by carhartl** [comment]
Though the 301 doesn't have anything to do with it. The link is simply broken, it was introduced here: 5421819450666bada6d1aed655cfaf4e85a4f88b

I say we're going to remove it.

**Comment by FagnerMartinsBrack** [comment]
+1 then, it seems nobody is relying on this, otherwise something would have popped up already.

**Comment by wilmoore** [comment]
> can you confirm if this still matters

I personally do not have a use for this going forward. The one client that was using volo moved directly to npm. I would hope anyone having this problem would just move to npm as well :smile:

**Pull request merged**
