### PR TITLE
Add Composer support

### PR DESCRIPTION
**Pull request by RobLoach**
This adds support for [Composer](https://getcomposer.org/), as referenced in #220.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for the PR!

We have a history of some package managers that were requested but didn't had enough notoriety  to be supported in the long run, [like this one](https://github.com/carhartl/jquery-cookie/pull/260#issuecomment-93535347). Regarding composer, there is a similar request where the OP found a workaround: https://github.com/carhartl/jquery-cookie/issues/220#issuecomment-25412945.

Also, we are not maintaining this repository anymore. The whole development was moved to https://github.com/js-cookie/js-cookie, we encourage everyone to download the latest releases: https://github.com/js-cookie/js-cookie/releases

**Comment by RobLoach** [comment]
@FagnerMartinsBrack Thanks, I've pushed that up here: https://github.com/RobLoach/js-cookie/pull/1 . Regarding your worry of un-maintained package management, Packagist does the release management for us, which makes your job a non-issue.

Whether it's brought in or not, I appreciate your looking into this, and all the work you've done on this :+1: .

**Comment by FagnerMartinsBrack** [comment]
Thanks xD

Let's continue in the other repository then.

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/issues/172#issuecomment-209286184 for detailed explanations of how to make js-cookie working with composer.

**Pull request closed without merging**
